// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeax0UcD_tuoSWIeO_ZtMJZMiU353WMyo',
    appId: '1:166195293260:android:8485793cd651eba467d8e9',
    messagingSenderId: '166195293260',
    projectId: 'countsip-prod',
    storageBucket: 'countsip-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBmnmF_yc2mpjz79ugcz5PjBZxosF-LzM',
    appId: '1:166195293260:ios:093cf61eaf251bef67d8e9',
    messagingSenderId: '166195293260',
    projectId: 'countsip-prod',
    storageBucket: 'countsip-prod.firebasestorage.app',
    iosBundleId: 'com.countsip.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeax0UcD_tuoSWIeO_ZtMJZMiU353WMyo',
    appId: '1:166195293260:web:countsip-web',
    messagingSenderId: '166195293260',
    projectId: 'countsip-prod',
    authDomain: 'countsip-prod.firebaseapp.com',
    storageBucket: 'countsip-prod.firebasestorage.app',
  );
}
